<!DOCTYPE html>

<!--

Created by: Isobel Lennox
For the Class:  CTEC126
Assignment: Homework 7
Date: 10/21/2014


-->



<html lang="en">

<head>
    <title>Isobel Lennox</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="css/style.css" rel="stylesheet" media="screen"> 
   <link href='http://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>
</head>

<body>